name: Python Package CI/CD
env:
  TWINE_USERNAME: __token__ # PyPI Username für Token
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    # manuelles Ausführen möglich

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # beliebige Python Version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine pytest

    - name: Run tests
      run: |
        pytest  # falls du Tests hast

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      if: github.event_name == 'push'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
